PaisaSavvy.value('Config', {
    API: {
        base: 'https://www.paisasavvy.com',
        // 
        getOTP: "/api/v2/getOTP",
        verifyOTP: "/api/v2/verifyOTP",
        doLogout: "/api/v2/doLogout",
        KYCCheck: "/api/v2/getKYC",
        getIFSC: "/api/v2/getIFSC",
        getEKYCLink: "/api/v2/getEKYCLink",
        updateFATCA: "/api/v2/updateFATCA",
        updateUserFolio: "/api/v2/updateUserFolio",
        getAccountBalance: "/api/v2/getAccountBalance",
        getPaymentLink: "/api/v2/getPaymentLink",
        reportTransaction: "/api/v2/reportTransaction",
        updatePassbook: "/api/v2/updatePassbook",
        doWithdraw: "/api/v2/doWithdraw",
        applyForDebitCard: "/api/v2/applyForDebitCard",
    },
    MobilePath: {
        home: "/mobile/",
        login: "/mobile/login",
        AadhaarKYC: "/mobile/AadhaarKYC",
        KYCCheck: "/mobile/KYCCheck",
        KYCReCheck: "/mobile/KYCReCheck",
        ClientDetails: "/mobile/ClientDetails",
        CreateFolio: "/mobile/CreateFolio",
        MyAccount: "/mobile/MyAccount",
        debitCardApplication: "/mobile/debitCardApplication",
    },
    Path: {
        home: "/",
        login: "/login",
        AadhaarKYC: "/AadhaarKYC",
        KYCCheck: "/KYCCheck",
        KYCReCheck: "/KYCReCheck",
        KarvyKYC: "/KarvyKYC",
        ClientDetails: "/ClientDetails",
        CreateFolio: "/CreateFolio",
        MyAccount: "/MyAccount",
        debitCardApplication: "/debitCardApplication",
    },
});